verbs_en = [
    # [infinitive en (0), past simple (1), past participle (2), infinive fr (3), translation fr (4), translation en (5)]
    ["abide", "abode", "abode", "demeurer", "demeurer", "abide"],
    ["arise", "arose", "arisen", "s'élever, survenir", "s'élever, survenir", "arise"],
    ["awake", "awoke", "awoken", "(se) réveiller", "se réveiller, réveiller", "awake, wake"],
    ["bear", "bore", "borne", "supporter", "supporter", "bear"],
    ["beat", "beat", "beaten", "battre", "battre", "beat"],
    ["become", "became", "become", "devenir", "devenir", "become"],
    ["begin", "began", "begun", "commencer", "commencer", "begin"],
    ["bend", "bent", "bent", "(se) courber", "se courber, courber", "bend"],
    ["bet", "bet", "bet", "parier", "parier", "bet"],
    ["bid", "bid", "bid", "offrir (un prix)", "offrir un prix, offrir", "bid"],
    ["bind", "bound", "bound", "lier, relier", "lier, relier", "bind"],
    ["bite", "bit", "bitten", "mordre", "mordre", "bite"],
    ["bleed", "bled", "bled", "saigner", "saigner", "bleed"],
    ["blow", "blew", "blown", "souffler", "souffler", "blow"],
    ["break", "broke", "broken", "casser", "casser", "break"],
    ["breed", "bred", "bred", "élever (du bétail)", "élever du bétail, élever", "breed"],
    ["bring", "brought", "brought", "apporter", "apporter", "bring"],
    ["build", "built", "built", "construire", "construire", "build"],
    ["burn", "burnt", "burnt", "brûler", "brûler", "burn"],
    ["burst", "burst", "burst", "éclater", "éclater", "burst"],
    ["buy", "bought","bought","acheter","acheter","buy"],
    ["cast", "cast", "cast", "jeter, lancer", "jeter, lancer", "cast"],
    ["catch", "caught", "caught", "attraper", "attraper", "catch"],
    ["choose", "chose", "chosen", "choisir", "choisir", "choose"],
    ["cling", "clung", "clung", "s'accrocher", "s'accrocher", "cling"],
    ["come", "came", "come", "venir", "venir", "come"],
    ["cost", "cost", "cost", "coûter", "coûter", "cost"],
    ["creep", "crept", "crept", "ramper", "ramper", "creep"],
    ["cut", "cut", "cut", "couper", "couper", "cut"],
    ["deal", "dealt", "dealt", "distribuer", "distribuer", "deal"],
    ["dig", "dug", "dug", "creuser", "creuser", "dig"],
    ["do", "did", "done", "faire", "faire", "do"],
    ["draw", "drew", "drawn", "dessiner", "dessiner", "draw"],
    ["dream", "dreamt", "dreamt", "rêver", "rêver", "dream"],
    ["drink", "drank", "drunk", "boire", "boire", "drink"],
    ["drive", "drove", "driven", "conduire", "conduire", "drive"],
    ["dwell", "dwelt", "dwelt", "habiter", "habiter", "dwell"],
    ["eat", "ate", "eaten", "manger", "manger", "eat"],
    ["fall", "fell", "fallen", "tomber", "tomber", "fall"],
    ["feed", "fed", "fed", "nourrir", "nourrir", "feed"],
    ["feel", "felt", "felt", "(se) sentir, éprouver", "se sentir, sentir, éprouver", "feel"],
    ["fight", "fought", "fought", "combattre, se battre", "combattre, se battre", "fight"],
    ["find", "found", "found", "trouver", "trouver", "find"],
    ["flee", "fled", "fled", "s'enfuir", "s'enfuir", "flee"],
    ["fling", "flung", "flung", "jeter violemment", "jeter violemment", "fling"],
    ["fly", "flew", "flown", "voler", "voler", "fly"],
    ["forbid", "forbade", "forbidden", "interdire", "interdire", "forbid"],
    ["forget", "forgot", "forgotten", "oublier", "oublier", "forget"],
    ["forgive", "forgave", "forgiven", "pardonner", "pardonner", "forgive"],
    ["freeze", "froze", "frozen", "geler", "geler", "freeze"],
    ["get", "got", "got", "obtenir, recevoir", "obtenir, recevoir", "get"],
    ["give", "gave", "given", "donner", "donner", "give"],
    ["go", "went", "gone", "aller", "aller", "go"],
    ["grind", "ground", "ground", "moudre", "moudre", "grind"],
    ["grow", "grew", "grown", "grandir", "grandir", "grow"],
    ["hang", "hung", "hung", "pendre, accrocher", "pendre, accrocher", "hang"],
    ["have", "had", "had", "avoir", "avoir", "have"],
    ["hear", "heard", "heard", "entendre", "entendre", "hear"],
    ["hide", "hid", "hidden", "(se) cacher", "se cacher, cacher", "hide" ],
    ["hit", "hit", "hit", "frapper, atteindre", "frapper, atteindre", "hit"],
    ["hold", "held", "held", "tenir", "tenir", "hold"],
    ["hurt", "hurt", "hurt", "blesser", "blesser", "hurt"],
    ["keep", "kept", "kept", "garder", "garder", "keep"],
    ["kneel", "knelt", "knelt", "s'agenouiller", "s'agenouiller", "kneel"],
    ["know", "knew", "known", "savoir, connaître", "savoir, connaître", "know"],
    ["lay", "laid", "laid", "poser à plat", "poser à plat", "lay"],
    ["lead", "led", "led", "mener", "mener", "lead"],
    ["lean", "leant", "leant", "s'appuyer", "s'appuyer", "lean"],
    ["leap", "leapt", "leapt", "sauter", "sauter", "leap, jump, spring"],
    ["learn", "learnt", "learnt", "apprendre", "apprendre", "learn"],
    ["leave", "left", "left", "laisser, quitter, partir", "laisser, quitter, partir", "leave"],
    ["lend", "lent", "lent", "prêter", "prêter", "lend"],
    ["let", "let", "let", "permettre, louer, laisser", "permettre, louer, laisser", "let"],
    ["lie", "lay", "lain", "être étendu / couché", "être étendu, être couché", "lie"],
    ["light", "lit", "lit", "allumer", "allumer", "light"],
    ["lose", "lost", "lost", "perdre", "perdre", "lose"],
    ["make", "made", "made", "faire, fabriquer", "faire, fabriquer", "make"],
    ["mean", "meant", "meant", "signifier", "signifier", "mean"],
    ["meet", "met", "met", "(se) rencontrer", "se rencontrer, rencontrer", "meet"],
    ["mow", "mowed", "mown", "tondre", "tondre", "mow"],
    ["overcome", "overcame", "overcome", "surmonter, vaincre", "surmonter, vaincre", "overcome"],
    ["pay", "paid", "paid", "payer", "payer", "pay"],
    ["put", "put", "put", "mettre", "mettre", "put"],
    ["quit", "quit", "quit", "cesser (de), quitter", "cesser de, cesser, quitter", "quit"],
    ["read", "read", "read", "lire", "lire", "read"],
    ["rid", "rid", "rid", "débarrasser", "débarrasser", "rid"],
    ["ride", "rode", "ridden", "chevaucher,", "chevaucher, monter à cheval", "ride"],
    ["ring", "rang", "rung", "sonner", "sonner", "ring"],
    ["rise", "rose", "risen", "s'élever, se lever", "s'élever, se lever", "rise"],
    ["run", "ran", "run", "courir", "courir", "run"],
    ["saw", "sawed", "sawn", "scier", "scier", "saw"],
    ["say", "said", "said", "dire", "dire", "say"],
    ["see", "saw", "seen", "voir", "voir", "see"],
    ["seek", "sought", "sought", "chercher", "chercher", "seek"],
    ["sell", "sold", "sold", "vendre", "vendre", "sell"],
    ["send", "sent", "sent", "envoyer", "envoyer", "send"],
    ["set", "set", "set", "fixer", "fixer", "set"],
    ["sew", "sewed", "sewn", "coudre", "coudre", "sew"],
    ["shake", "shook", "shaken", "secouer", "secouer", "shake"],
    ["shear", "sheared", "shorn", "tondre (des moutons)", "tondre des moutons, tondre", "shear"],
    ["shed", "shed", "shed", "verser (des larmes)", "verser des larmes, verser", "shed"],
    ["shine", "shone", "shone", "briller", "briller", "shine"],
    ["shoe", "shod", "shod", "ferrer, chausser", "ferrer, chausser", "shoe"],
    ["shoot", "shot", "shot", "tirer", "tirer", "shoot"],
    ["show", "showed", "shown", "montrer", "montrer", "show"],
    ["shrink", "shrank", "shrunk", "rétrécir", "rétrécir", "shrink"],
    ["shut", "shut", "shut", "fermer", "fermer", "shut"],
    ["sing", "sang", "sung", "chanter", "chanter", "sing"],
    ["sink", "sank", "sunk", "couler", "couler", "sink"],
    ["sit", "sat", "sat", "être assis", "être assis", "sit"],
    ["sleep", "slept", "slept", "dormir", "dormir", "sleep"],
    ["slide", "slid", "slid", "glisser", "glisser", "slide"],
    ["sling", "slung", "slung", "lancer (avec force)", "lancer avec force, lancer", "sling"],
    ["slink", "slunk", "slunk", "se faufiler", "aller furtivement, se faufiler, se glisser", "slink"],
    ["slit", "slit", "slit", "fendre, inciser", "fendre, inciser", "slit"],
    ["smell", "smelt", "smelt", "sentir (odorat)", "sentir", "smell"],
    ["sow", "sowed", "sown", "semer", "semer", "sow"],
    ["speak", "spoke", "spoken", "parler", "parler", "speak"],
    ["speed", "sped", "sped", "aller à toute vitesse", "aller à toute vitesse", "speed"],
    ["spell", "spelt", "spelt", "épeler", "épeler", "spell"],
    ["spend", "spent", "spent", "dépenser", "dépenser", "spend"],
    ["spill", "spilt", "spilt", "renverser (un liquide)", "renverser un liquide, renverser", "spill"],
    ["spit", "spat", "spat", "cracher", "cracher", "spit"],
    ["split", "split", "split", "fendre", "fendre", "split"],
    ["spoil", "spoilt", "spoilt", "gâcher, gâter", "gâcher, gâter", "spoil"],
    ["spread", "spread", "spread", "répandre, étaler", "répandre, étaler", "spread"],
    ["spring", "sprang", "sprung", "jaillir, bondir, sauter", "jaillir, bondir, sauter", "spring"],
    ["stand", "stood", "stood", "être debout", "être debout", "stand"],
    ["steal", "stole", "stolen", "voler, dérober", "voler, dérober", "steal"],
    ["stick", "stuck", "stuck", "coller", "coller", "stick"],
    ["sting", "stung", "stung", "piquer", "piquer", "sting"],
    ["stink", "stank", "stunk", "puer", "puer", "stink"],
    ["stride", "strode", "stridden", "marcher à grands pas", "marcher à grands pas", "stride"],
    ["strike", "struck", "struck", "frapper", "frapper", "strike"],
    ["string", "strung", "strung", "enfiler, tendre (une corde)", "enfiler, tendre une corde, tendre", "string"],
    ["strive", "strove", "striven", "s'efforcer", "s'efforcer", "strive"],
    ["swear", "swore", "sworn", "jurer", "jurer, promettre", "swear"],
    ["sweep", "swept", "swept", "balayer", "balayer", "sweep"],
    ["swell", "swelled", "swollen", "enfler", "enfler", "swell"],
    ["swim", "swam", "swum", "nager", "nager", "swim"],
    ["swing", "swung", "swung", "(se) balancer", "se balancer, balancer", "swing"],
    ["take", "took", "taken", "prendre", "prendre", "take"],
    ["teach", "taught", "taught", "enseigner", "enseigner", "teach"],
    ["tear", "tore", "torn", "déchirer", "déchirer", "tear"],
    ["tell", "told", "told", "dire, raconter", "dire, raconter", "tell"],
    ["think", "thought", "thought", "penser", "penser", "think"],
    ["throw", "threw", "thrown", "jeter, lancer", "jeter, lancer", "throw"],
    ["thrust", "thrust", "thrust", "enfoncer", "enfoncer", "thrust"],
    ["tread", "trod", "trodden", "fouler aux pieds", "fouler aux pieds", "tread"],
    ["undergo", "underwent", "undergone", "subir", "subir", "undergo"],
    ["understand", "understood", "understood", "comprendre", "comprendre", "understand"],
    ["upset", "upset", "upset", "bouleverser", "bouleverser", "upset"],
    ["wear", "wore", "worn", "porter (des vêtements)", "porter des vêtements, porter", "wear"],
    ["weave", "wove", "woven", "tisser", "tisser", "weave"],
    ["weep", "wept", "wept", "pleurer", "pleurer", "weep"],
    ["win", "won", "won", "gagner", "gagner", "win"],
    ["wind", "wound", "wound", "enrouler", "enrouler", "wind"],
    ["withdraw", "withdrew", "withdrawn", "(se) retirer", "se retirer, retirer", "withdraw"],
    ["wring", "wrung", "wrung", "tordre", "tordre", "wring"],
    ["write", "wrote", "written", "écrire", "écrire", "write"]
]

verbs_nl = [
    # [infinitive nl (0), past simple (1), past participle (2), infinitive fr (3), translation fr (4), translation nl (5)]
    ["aankommen", "kwamen aan", "aangekomen", "arriver", "arriver", "aankommen"],
    ["aanwerven", "wierven aan", "aangeworven", "recruter, engager", "recruter, engager", "aanwerven"],
    ["afspreken", "spraken af", "afgesproken", "convenir de", "convenir de, convenir", "afspreken"],
    ["bakken", "bakten", "gebakken", "cuire", "cuire", "bakken"],
    ["barsten", "barstten", "gebarsten", "éclater", "éclater", "barsten"],
    ["bedriegen", "bedrogen", "bedrogen", "tromper", "tromper", "bedriegen"],
    ["beginnen", "begonnen", "begonnen", "commencer", "commencer", "beginnen"],
    ["begrijpen", "begrepen", "begrepen", "comprendre", "comprendre", "begrijpen"],
    ["beschrijven", "beschreven", "beschreven", "décrire", "décrire", "beschrijven"],
    ["besluiten", "besloten", "besloten", "décider", "décider", "besluiten"],
    ["bestaan", "bestonden", "bestaan", "exister", "exister", "bestaan"],
    ["bevelen", "bevalen", "bevolen", "ordeonner", "ordeonner", "bevelen"],
    ["bewegen", "bewogen", "bewogen", "bouger", "bouger", "bewegen"],
    ["bezoeken", "bezochten", "bezocht", "visiter", "visiter", "bezoeken"],
    ["bidden", "baden", "gebeden", "prier", "prier", "bidden"],
    ["bieden", "boden", "geboden", "offrir", "offrir", "bieden"],
    ["bijten", "beten", "gebeten", "mordre", "mordre", "bijten"],
    ["binden", "bonden", "gebonden", "lier", "lier", "binden"],
    ["blazen", "bliezen", "geblazen", "souffler", "souffler", "blazen"],
    ["blijken", "bleken", "gebeleken", "sembler", "sembler", "blijken"],
    ["blijven", "bleven", "gebleven", "rester", "rester", "blijven"],
    ["braden", "braaden", "gebraden", "rôtir", "rôtir", "braden"],
    ["breken", "braken", "gebroken", "casser", "casser", "breken"],
    ["brengen", "brachten", "gebracht", "apporter", "apporter", "brengen"],
    ["brouwen", "brouwden", "gebrouwen", "brasser", "brasser", "brouwen"],
    ["buigen", "bogen", "gebogen", "courber", "courber", "buigen"],
    ["deelnemen", "namen deel", "deelgenomen", "prendre part à ", "prendre part à ", "deelnemen"],
    ["denken", "dachten", "gedacht", "penser à", "penser à", "denken"],
    ["doen", "deden", "gedaan", "faire", "faire", "doen"],
    ["doorbrengen", "brachten door", "doorgebracht", "passer (du temps)", "passer du temps, passer", "doorbrengen"],
    ["dragen", "droegen", "gedragen", "porter (vêtement)", "porter des vêtements, porter", "dragen"],
    ["drinken", " dronken", "gedronken", "boire", "boire", "drinken"],
    ["duiken", "doken", "gedoken", "plonger", "plonger", "duiken"],
    ["dwingen", "dwongen", "gedwongen", "forcer", "forcer", "dwingen"],
    ["eten", "aten", "gegeten", "manger", "manger", "eten"],
    ["fluiten", "floten", "gefloten", "siffler", "siffler", "fluiten"],
    ["gaan", "gingen", "gegaan", "aller", "aller", "gaan"],
    ["gelden", "golden", "gegolden", "valoir", "valoir", "gelden"],
    ["genezen", "genazen", "genezen", "guérir", "guérir", "genezen"],
    ["genieten", "genoten", "genoten", "jouir, apprécier", "jouir, apprécier", "genieten"],
    ["geven", "gaven", "gegeven", "donner", "donner", "geven"],
    ["gieten", "goten", "gegoten", "verser", "verser", "gieten"],
    ["glijden", "gleden", "gegleden", "glisser", "glisser", "glijden"],
    ["graven", "groeven", "gegraven", "creuser", "creuser", "graven"],
    ["grijpen", "grepen", "gegrepen", "saisir", "saisir", "grijpen"],
    ["hangen", "hingen", "gehangen", "être suspendu, pendre", "être suspendu, pendre", "hangen"],
    ["hebben", "hadden", "gehad", "avoir", "avoir", "hebben"],
    ["helpen", "hielpen", "geholpen", "aider", "aider", "helpen"],
    ["heten", "heetten", "geheten", "s'appeler", "s'appeler", "heten"],
    ["houden (van)", "hielden", "gehouden", "aimer", "aimer", "houden van, houden"],
    ["jagen", "joegen", "gejaagd", "chasser", "chasser", "jagen"],
    ["kiezen", "kozen", "gekozen", "choisir", "choisir", "kiezen"],
    ["kijken (naar)", "keken", "gekeken", "regarder", "regarder", "kijken naar, kijken"],
    ["klimmen", "klommen", "geklommen", "grimper", "grimper", "klimmen"],
    ["klinken", "klonken", "geklonken", "résonner", "résonner", "klinken"],
    ["komen", "kwamen", "gekomen", "venir", "venir", "komen"],
    ["kopen", "kochten", "gekocht", "acheter", "acheter", "kopen"],
    ["krijgen", "kregen", "gekregen", "obtenir, recevoir", "obtenir, recevoir", "krijgen"],
    ["kunnen", "konden", "gekund", "pouvoir (capacité)", "pouvoir", "kunnen"],
    ["lachen", "lachten", "gelachen", "rire", "rire", "lachen"],
    ["laden", "laadden", "geladen", "charger", "charger", "laden"],
    ["laten", "lieten", "gelaten", "laisser", "laisser", "laten"],
    ["lezen", "lazen", "gelezen", "lire", "lire", "lezen"],
    ["liegen", "logen", "gelogen", "mentir", "mentir", "liegen"],
    ["liggen", "lagen", "gelegen", "être couché", "être couché", "liggen"],
    ["lijden", "leden", "geleden", "souffrir", "souffrir", "lijden"],
    ["lijken", "leken", "geleken", "paraître, sembler", "paraître, sembler", "lijken"],
    ["lijken op", "leken op", "geleken op", "ressembler à", "ressembler à, ressembler", "lijken op"],
    ["lopen", "liepen", "gelopen", "marcher, courir", "marcher, courir", "lopen"],
    ["meedoen", "deden mee", "meegedaan", "participer", "participer", "meedoen"],
    ["meenemen", "namen mee", "meegenomen", "prendre avec soi", "prendre avec soi", "meenemen"],
    ["meten", "maten", "gemeten", "mesurer", "mesurer", "meten"],
    ["moeten", "moesten", "gemoeten", "devoir (obligation)", "devoir", "moeten"],
    ["mogen", "mochten", "gemogen", "pouvoir (permission)", "pouvoir", "mogen"],
    ["nadenken (over)", "dachten na", "nagedacht", "réfléchir à", "réfléchir à, réfléchir", "nadenken over, nadenken"],
    ["nemen", "namen", "genomen", "prendre", "prendre", "nemen"],
    ["ontbijten", "ontbeten", "ontbeten", "déjeuner", "déjeuner", "ontbijten"],
    ["ontstaan", "ontsonden", "ontsaan", "apparaître, naître", "apparaître, naître", "ontstaan"],
    ["opnemen", "namen op", "opgenomen", "enregistrer", "enregistrer", "opnemen"],
    ["opschieten", "schoten op", "opgeschoten", "se dépêcher", "se dépêcher", "opschieten"],
    ["opstaan", "stonden op", "opgestaan", "se lever (le matin)", "se lever", "opstaan"],
    ["overdrijven", "overdreven", "overdreven", "exagérer", "exagérer", "overdrijven"],
    ["overseteken", "staken over", "overgestoken", "traverser", "traverser", "overseteken"],
    ["paardrijden", "reden paard", "paardgereden", "faire de l'équitation", "faire de l'équitation", "paardrijden"],
    ["plaatsvinden", "vondern plaats", "plaatsgevonden", "avoir lieu", "avoir lieu", "plaatsvinden"],
    ["raden", "raaden", "geraden", "deviner", "deviner", "raden"],
    ["rijden", "reden", "gereden", "rouler", "rouler", "rijden"],
    ["roepen", "riepen", "geroepen", "crier, appeler", "crier, appeler", "roepen"],
    ["ruiken", "roken", "geroken", "sentir", "sentir", "ruiken"],
    ["scheiden", "scheiden", "gescheiden", "séparer", "séparer", "scheiden"],
    ["schenken", "schonken", "geschonken", "donner (un cadeau)", "donner un cadeau, donner", "schenken"],
    ["scheren", "schoren", "geschoren", "raser", "raser", "scheren"],
    ["schieten", "schoten", "geschoten", "tirer (avec une arme)", "tirer avec une arme, tirer", "schieten"],
    ["schijnen", "schenen", "geschenen", "briller, sembler", "briller, sembler", "schijnen"],
    ["schrijven", "scheven", "gescheven", "écrire", "écrire", "schrijven"],
    ["schrikken", "schrokken", "geschrokken", "avoir peur", "avoir peur", "schrikken"],
    ["schuiven", "schoven", "geschoven", "(faire) glisser", "faire glisser, glisser", "schuiven"],
    ["slaan", "sloegen", "geslagen", "frapper", "frapper", "slaan"],
    ["slapen", "sliepen", "geslapen", "dormir", "dormir", "slapen"],
    ["sluiten", "sloten", "gesloten", "fermer", "fermer", "sluiten"],
    ["smelten", "smolten", "gesmolten", "fondre", "fondre", "smelten"],
    ["snijden", "sneden", "gesneden", "couper", "couper", "snijden"],
    ["spreken", "spraken", "gesproken", "parler", "parler", "spreken"],
    ["springen", "sprongen", "gesprongen", "sauter", "sauter", "springen"],
    ["staan", "stonden", "gestaan", "être debout", "être debout", "staan"],
    ["steken", "staken", "gestoken", "piquer", "piquer", "steken"],
    ["stelen", "stalen", "gestolen", "voler, dérober", "voler, dérober", "stelen"],
    ["sterven", "stierven", "gestorven", "mourir", "mourir", "sterven"],
    ["stijgen", "stegen", "gestegen", "monter", "monter", "stijgen"],
    ["stinken", "stonken", "gestonken", "puer", "puer", "stinken"],
    ["strijden", "streden", "gestreden", "combattre", "combattre", "strijden"],
    ["strijken", "streken", "gestreken", "repasser (du linge)", "repasser du linge, repasser", "strijken"],
    ["tegenkomen", "kwamen tegen", "tegengekomen", "recontrer", "recontrer", "tegenkomen"],
    ["treffen", "troffen", "getroffen", "toucher", "toucher", "treffen"],
    ["trekken", "trokken", "getrokken", "tirer", "tirer", "trekken"],
    ["uitlaten", "lieten uit", "uitgelaten", "faire sortir (le chien)", "faire sortir le chien, faire sortir", "uitlaten"],
    ["uitschelden", "sholden uit", "uitgescholden", "insulter", "insulter", "uitschelden"],
    ["uitspreken", "spraken uit", "uitgesproken", "prononcer", "prononcer", "uitspreken"],
    ["uitvinden", "vonden uit", "uitgevonden", "inventer", "inventer", "uitvinden"],
    ["vallen", "vielen", "gevallen", "tomber", "tomber", "vallen"],
    ["varen", "voeren", "gevaren", "naviguer", "naviguer", "varen"],
    ["vechten", "vochten", "gevochten", "se battre", "se battre", "vechten"],
    ["verbieden", "verboden", "verboden", "interdire", "interdire", "verbieden"],
    ["verbinden", "verbonden", "verbonden", "relier", "relier", "verbinden"],
    ["verdwijnen", "verdwenen", "verdwenen", "disparaître", "disparaître", "verdwijnen"],
    ["vergeten", "vergaten", "vergeten", "oublier", "oublier", "vergeten"],
    ["verkopen", "verkochten", "verkocht", "vendre", "vendre", "verkopen"],
    ["verlaten", "verlieten", "verlaten", "quitter, abandonner", "quitter, abandonner", "verlaten"],
    ["verliezen", "verloren", "verloren", "perdre", "perdre", "verliezen"],
    ["vermijden", "vermeden", "vermeden", "éviter", "éviter", "vermijden"],
    ["vertrekken", "vertrokken", "vertrokken", "partir", "partir", "vertrekken"],
    ["vinden", "vonden", "gevonden", "trouver", "trouver", "vinden"],
    ["vliegen", "vlogen", "gevlogen", "voler (en l'air)", "voler en l'air, voler", "vliegen"],
    ["voorzien", "voorzagen", "voorzien", "prévoir", "prévoir", "voorzien"],
    ["vragen", "vroegen", "gevraagd", "demander", "demander", "vragen"],
    ["vriezen", "vroren", "gevroren", "geler", "geler", "vriezen"],
    ["wassen", "wasten", "gewassen", "laver", "laver", "wassen"],
    ["wegen", "wogen", "gewogen", "peser", "peser", "wegen"],
    ["werpen", "wierpen", "geworpen", "jeter, lancer", "jeter, lancer", "werpen"],
    ["weten", "wisten", "geweten", "savoir", "savoir", "weten"],
    ["wijzen", "wezen", "gewezen", "montrer, indiquer", "montrer, indiquer", "wijzen"],
    ["winnen", "wonnen", "gewonnen", "gagner", "gagner", "winnen"],
    ["worden", "werden", "geworden", "devenir", "devenir", "worden"],
    ["zeggen", "zeiden", "gezegd", "dire, affirmer", "dire, affirmer", "zeggen"],
    ["zenden", "zonden", "gezonden", "envoyer", "envoyer", "zenden"],
    ["zien", "zagen", "gezien", "voir", "voir", "zien"],
    ["zijn", "waren", "geweest", "être", "être", "zijn"],
    ["zingen", "zongen", "gezongen", "chanter", "chanter", "zingen"],
    ["zinken", "zonken", "gezonken", "sombrer, couler", "sombrer, couler", "zinken"],
    ["zitten", "zaten", "gezeten", "être assis", "être assis", "zitten"],
    ["zoeken", "zochten", "gezocht", "chercher", "chercher", "zoeken"],
    ["zwellen", "zwollen", "gezwollen", "enfler, gonfler", "enfler, gonfler", "zwellen"],
    ["zwemmen", "zwommen", "gezwommen", "nager", "nager", "zwemmen"],
    ["zweren", "zwoeren", "gezwoeren", "jurer (serment)", "jurer", "zweren"],
    ["zwijgen", "zwegen", "gezwegen", "se taire", "se taire", "zwijgen"]
]
